### ISSUE TITLE
Unable to connect to host (harbor registry)

### ISSUE THREAD

**Issue by sh3tb3rd** [deep-security/smartcheck-helm#11]
Ubuntu 18.04.2 
kubectl: 1.15 (1x master, 2x worker)
docker: 18.09.5
smartcheck: 1.2.9

Hi, 
after helm install, all smartcheck pods are Running. When I try to add my Harbor Registry (v1.7.5) smartcheck shows me Registry Host xxx.xxx.xxx.xxx unable to connect to host. I tried to skip the certificate validation and user & pass are also right. 

Ping and docker login to the harbor host is successfull. Also connecting to the Harbor Web Interface over the browser and URL is successfull. The hosts file is also up-to-date.
Can somebody help?

> admin@kubemaster01:~$ kubectl logs -f -n smartcheck registryviews-f6b7f4977-658sq
>  
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Making HTTP request","method":"POST","request":"POST /api/authorizations HTTP/1.1\r\nHost: auth-internal:8081\r\nConnection: close\r\nAccept: application/json,/\r\nContent-Type: application/json\r\nUser-Agent: unknown\r\n\r\n","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T08:58:48Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Received HTTP response","method":"POST","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","response":"HTTP/1.1 201 Created\r\nConnection: close\r\nContent-Length: 552\r\nCache-Control: no-cache,no-store,must-revalidate\r\nContent-Security-Policy: default-src: 'none';block-all-mixed-content;disown-opener;reflected-xss filter\r\nContent-Type: application/json\r\nDate: Wed, 26 Jun 2019 08:58:48 GMT\r\nExpires: 0\r\nLocation: http://auth-internal:8081/api/authorizations/1d28f4f4-10a3-4003-9e25-ae2846ffcafd\r\nPragma: no-cache\r\nReferrer-Policy: no-referrer\r\nX-Api-Version: 2018-05-01\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: DENY\r\nX-Request-Id: 1d28f4f4-10a3-4003-9e25-ae2846ffcafd\r\nX-Xss-Protection: 1;mode=block\r\n\r\n","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T08:58:48Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","duration":1591420,"fields.level":"sql","level":"sql","message":"SQL statement","registry":"58003134-08de-48a8-9f80-36172b16938e","registryName":"harbor-reg","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","sql":"SELECT count() FROM "registries" WHERE (name = $1 AND pk != $2)","timestamp":"2019-06-26T08:58:48Z","values":["'harbor-reg'","'0'"]}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","message":"registry.ping url=https://192.xxx.xxx.xxx/v2/","registry":"58003134-08de-48a8-9f80-36172b16938e","registryName":"harbor-reg","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T08:58:48Z"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","error":"Get https://192.xxx.xxx.xxx/v2/: Get https://harbor/service/token?service=harbor-registry: dial tcp: lookup harbor on 10.96.0.10:53: no such host","message":"Unable to connect to registry","registry":"192.xxx.xxx.xxx","registryName":"harbor-reg","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"warning","timestamp":"2019-06-26T08:58:48Z"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","dur":"102.228189ms","len":161,"message":"Handled API request","method":"POST","peer":"10.244.1.64:55810","proto":"HTTP/1.0","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","response":400,"session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"info","timestamp":"2019-06-26T08:58:48Z","uri":"/api/registries?scan=false"}
> {"api":"external","component":"registryviews","insecureSkipVerify":false,"message":"Making HTTP request","method":"POST","request":"POST /api/authorizations HTTP/1.1\r\nHost: auth-internal:8081\r\nConnection: close\r\nAccept: application/json,/\r\nContent-Type: application/json\r\nUser-Agent: unknown\r\n\r\n","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","component":"registryviews","insecureSkipVerify":false,"message":"Received HTTP response","method":"POST","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","response":"HTTP/1.1 201 Created\r\nConnection: close\r\nContent-Length: 552\r\nCache-Control: no-cache,no-store,must-revalidate\r\nContent-Security-Policy: default-src: 'none';block-all-mixed-content;disown-opener;reflected-xss filter\r\nContent-Type: application/json\r\nDate: Wed, 26 Jun 2019 09:00:04 GMT\r\nExpires: 0\r\nLocation: http://auth-internal:8081/api/authorizations/f21f1975-4037-406f-8ac6-e1bab7720135\r\nPragma: no-cache\r\nReferrer-Policy: no-referrer\r\nX-Api-Version: 2018-05-01\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: DENY\r\nX-Request-Id: f21f1975-4037-406f-8ac6-e1bab7720135\r\nX-Xss-Protection: 1;mode=block\r\n\r\n","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Making HTTP request","method":"GET","request":"GET /api/license?entitlement=registries HTTP/1.1\r\nHost: license-internal:8081\r\nConnection: close\r\nUser-Agent: unknown\r\n\r\n","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://license-internal:8081/api/license?entitlement=registries"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Received HTTP response","method":"GET","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","response":"HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: 135\r\nCache-Control: no-cache\r\nCache-Control: no-cache,no-store,must-revalidate\r\nContent-Security-Policy: default-src: 'none';block-all-mixed-content;disown-opener;reflected-xss filter\r\nContent-Type: application/json\r\nDate: Wed, 26 Jun 2019 09:00:04 GMT\r\nExpires: 0\r\nPragma: no-cache\r\nReferrer-Policy: no-referrer\r\nX-Api-Version: 2018-05-01\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: DENY\r\nX-Request-Id: 364bf418-8790-499d-974f-1184dfe407af\r\nX-Xss-Protection: 1;mode=block\r\n\r\n","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://license-internal:8081/api/license?entitlement=registries"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","duration":1059303,"fields.level":"sql","level":"sql","message":"SQL statement","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","sql":"SELECT count() FROM "registries" ","timestamp":"2019-06-26T09:00:04Z","values":null}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Making HTTP request","method":"POST","request":"POST /api/authorizations HTTP/1.1\r\nHost: auth-internal:8081\r\nConnection: close\r\nAccept: application/json,/\r\nContent-Type: application/json\r\nUser-Agent: unknown\r\n\r\n","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","insecureSkipVerify":false,"message":"Received HTTP response","method":"POST","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","response":"HTTP/1.1 201 Created\r\nConnection: close\r\nContent-Length: 551\r\nCache-Control: no-cache,no-store,must-revalidate\r\nContent-Security-Policy: default-src: 'none';block-all-mixed-content;disown-opener;reflected-xss filter\r\nContent-Type: application/json\r\nDate: Wed, 26 Jun 2019 09:00:04 GMT\r\nExpires: 0\r\nLocation: http://auth-internal:8081/api/authorizations/4985f3b4-f5f9-414c-8aca-6c9b7d853eff\r\nPragma: no-cache\r\nReferrer-Policy: no-referrer\r\nX-Api-Version: 2018-05-01\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: DENY\r\nX-Request-Id: 4985f3b4-f5f9-414c-8aca-6c9b7d853eff\r\nX-Xss-Protection: 1;mode=block\r\n\r\n","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T09:00:04Z","url":"http://auth-internal:8081/api/authorizations"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","duration":2479475,"fields.level":"sql","level":"sql","message":"SQL statement","registry":"ac81c03d-45e9-482b-bd9c-df9f2106c63b","registryName":"harbor-reg","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","sql":"SELECT count(*) FROM "registries" WHERE (name = $1 AND pk != $2)","timestamp":"2019-06-26T09:00:04Z","values":["'harbor-reg'","'0'"]}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","message":"registry.ping url=https://192.xxx.xxx.xxx/v2/","registry":"ac81c03d-45e9-482b-bd9c-df9f2106c63b","registryName":"harbor-reg","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"debug","timestamp":"2019-06-26T09:00:04Z"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","error":"Get https://192.xxx.xxx.xxx/v2/: Get https://harbor/service/token?service=harbor-registry: dial tcp: lookup harbor on 10.96.0.10:53: no such host","message":"Unable to connect to registry","registry":"192.xxx.xxx.xxx","registryName":"harbor-reg","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"warning","timestamp":"2019-06-26T09:00:04Z"}
> {"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","dur":"139.274071ms","len":161,"message":"Handled API request","method":"POST","peer":"10.244.1.64:56978","proto":"HTTP/1.0","requestID":"798434d7-dc1e-4a26-8e3d-4c53ff301167","response":400,"session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"info","timestamp":"2019-06-26T09:00:04Z","uri":"/api/registries?scan=false"}

**Comment by glb** [comment]
Hi @sh3tb3rd! Thank you for providing the logs, that has really helped with the diagnosis. The key log is this one:

```txt
{"api":"external","auth-user":"5e204820-3a45-4652-bf71-e86a1a654b4b","auth-userid":"administrator","component":"registryviews","error":"Get https://192.xxx.xxx.xxx/v2/: Get https://harbor/service/token?service=harbor-registry: dial tcp: lookup harbor on 10.96.0.10:53: no such host","message":"Unable to connect to registry","registry":"192.xxx.xxx.xxx","registryName":"harbor-reg","requestID":"781f4942-6cea-4bb5-b13a-bb85b737619f","session":"03e1aa36-3ef2-4f60-814f-d7c4c6ca4edc","severity":"warning","timestamp":"2019-06-26T08:58:48Z"}
```

It looks like your Harbor instance thinks its hostname is `harbor`. When Deep Security Smart Check connects, Harbor is telling Deep Security Smart Check to get an OAuth token at `https://harbor/service/token?service=harbor-registry`, and when Deep Security Smart Check tries to resolve `harbor` it is failing to do so.

Check the docs for your version of Harbor to see how to configure the hostname (may also be referred to as FQDN -- fully-qualified domain name).

**Comment by sh3tb3rd** [comment]
I checked the following on my Harbor Instance:

```
admin@harbor:~$ hostname
harbor
```

hostname parameter in harbor.cfg
`hostname = harbor`

So that should be fine in my opinion. How can I configure the Kubernetes DNS that way that Smartcheck can find my harbor instance outside the pod network?

**Comment by glb** [comment]
Check out [Customizing DNS Service](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/) and [Debugging DNS Resolution](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) in the Kubernetes documentation, they may help. Once you have your Harbor instance resolving in a pod (see the process in the debugging page) then things should work better for Deep Security Smart Check.

You may need to configure Harbor with a fully-qualified domain name (something like `harbor.example.com` rather than just the hostname `harbor`) so that Kubernetes knows where to forward the DNS requests.
