### ISSUE TITLE
error with malware-scan

### ISSUE THREAD

**Issue by sinycn** [deep-security/smartcheck-helm#12]
when run smart scan i get one error:
[root@localhost kubernetes]# kubectl get pod
NAME                                  READY   STATUS             RESTARTS   AGE
auth-6dbd59bc4b-m7t29                 1/1     Running            0          115m
content-scan-85c467c9dd-7wmvr         1/1     Running            0          115m
db-b48d894bc-hgzg2                    1/1     Running            0          115m
docs-c97c55fdf-hw6tv                  1/1     Running            0          115m
frontend-dc9b6b5b-snbbh               1/1     Running            0          115m
license-787dbf7c69-4rzgm              1/1     Running            0          115m
malware-scan-8675c8d855-x6vrp         0/1     CrashLoopBackOff   27         115m
metrics-7588d659fc-5kvb6              1/1     Running            0          115m
nfs-provisioner-85fd9d6fc4-st7jg      1/1     Running            0          4h35m
openscap-scan-5f7f64db77-xfxkq        2/2     Running            0          115m
proxy-66d584c7-vtdzr                  1/1     Running            0          115m
registryviews-5f4c58794-5xg5v         1/1     Running            0          115m
scan-5b5cd569b7-8lrpv                 1/1     Running            0          115m
vulnerability-scan-6976ff9fbf-46zv2   1/1     Running            0          115m

and logs as blew:

[root@localhost kubernetes]# kubectl logs  malware-scan-8675c8d855-x6vrp
+ cp -a /home/smartcheck/patterns/icrc$oth.173 /home/smartcheck/patterns/icrc$oth.version /home/smartcheck/patterns/lastupdate /home/smartcheck/patterns/tmblack.251 /home/smartcheck/patterns/tmblack.version /home/smartcheck/patterns/trendx.112 /home/smartcheck/patterns/trendx.version .
+ ulimit -c unlimited
+ /home/smartcheck/vscansvc --license-url=http://license-internal:8081
{"buildTime":"","commit":"3d70b5e05caf3c27a2ba687ba97976d2e70e9914","message":"Starting up","severity":"audit","timestamp":"2019-07-02T14:08:29Z"}
{"message":"VSAPI version:  11.0.0.1006","severity":"info","timestamp":"2019-07-02T14:08:29Z"}
{"message":"iCRC version: 2.82.0.1036","severity":"info","timestamp":"2019-07-02T14:08:29Z"}
{"message":"TrendX version: 1.100.1047","severity":"info","timestamp":"2019-07-02T14:08:29Z"}
VSInit
VSSetPatternPath
{"message":"Error invoking scan service: scan engine init error -3 - VSReadVirusPattern failed with -3\n","severity":"fatal","timestamp":"2019-07-02T14:08:29Z"}
+ [ -f core* ]

**Comment by glb** [comment]
@sinycn that should definitely not be happening!

Could you share more information about your cluster? What version of Kubernetes is it running, where is it running (on-premises, GKE, EKS, ...), do you have a proxy configured, do you have any special setup on your worker nodes (anything that could be interfering with the normal operation of the malware scan pod)...

If you have a support contact with Trend Micro feel free to continue the conversation there.

**Comment by sinycn** [comment]
hi @glb 
Kubernetes version:
[root@localhost ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
2. running on-premises
3.no proxy configured
4.i set up k8s use ansible

**Comment by glb** [comment]
Thanks @sinycn ... I'm not seeing anything in that setup that should cause this sort of behaviour. I'll do some investigation and get back to you.

**Comment by glb** [comment]
@sinycn could you please try again with [the latest release](https://github.com/deep-security/smartcheck-helm/releases/tag/1.2.14)?

**Comment by glb** [comment]
The issue has been resolved with the new release.
