### ISSUE TITLE
Ingress Support

### ISSUE THREAD

**Issue by winggundamth** [deep-security/smartcheck-helm#16]
Our use case
- We use AWS with one ingress for all public traffic to reduce our cost on load balancer
- For on-premise we can reduce the rule on load balancer to point only one ingress
- We use cert-manager to auto-generate ssl certificates.

**Comment by glb** [comment]
Thanks for the input @winggundamth ! 

Your use case of consolidating all public traffic onto one load balancer is more advanced than what this chart is intended to support, but it's certainly possible to set up your own `Ingress` to forward traffic to the `proxy` pod and change the `proxy` `Service` to be local to the cluster. 

Hope this helps!
