### ISSUE TITLE
Supplised Database pod fails with persistence enabled

### ISSUE THREAD

**Issue by Jonher937** [deep-security/smartcheck-helm#19]
# Database deployment fails due to permission denied

It looks like the `PGDATA` path needs to be changed or the permissions in the image.
Using the supplied db in the chart with persistence causes this:

```
  {"timestamp":"2020-09-26T18:32:40Z","severity":"info","message":"starting"}
  mkdir: can't create directory '/var/lib/postgresql/data/pgdata': Permission denied
```

Changing `PGDATA` from the default to `/var/lib/postgresql/pgdata` makes it work

**Comment by henryguan** [comment]
Hi Jonher937, can you share what your overrides.yaml looks like ?

**Comment by Jonher937** [comment]
# Overrides

```yaml
persistence:
  enabled: true
  storageClassName: longhorn
```

**Comment by Jonher937** [comment]
OK so I looked into this a bit more, you can discard of the inital post, it looks like it's actually a problem with the `chmod` process not having permissions to chmod whenever persistence is enabled.

```
{"timestamp":"2020-09-29T10:33:04Z","severity":"info","message":"starting"}
chmod: /var/lib/postgresql/data: Operation not permitted
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ...
```

**Comment by henryguan** [comment]
You might disabled securityContext. SecurityContext needs to be enabled so that Kubernetes can specify correct value for fsGroup and runAsUser.  Please have a look at values.yaml. 
You can get DB image on docker.io: 
docker pull deepsecurity/db
