### ISSUE TITLE
Error unable to extract tarball: chart illegally contains content outside the base directory: "._helm"

### ISSUE THREAD

**Issue by rameshkjha** [deep-security/smartcheck-helm#20]
Here is my chart directory structure.
helm
/templates/
Chart.yaml
values.yaml
I am packaging helm directory, when I run helm lint on the generated package *.tgz file it is throwing this error.

==> Linting my_package_file.tgz
Error unable to extract tarball: chart illegally contains content outside the base directory: "._helm"

Error: 1 chart(s) linted, 1 chart(s) failed.

Helm version in use - Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

**Comment by holyspectral** [comment]
Hi @rameshkjha , 

How did you create the tgz file?  I tried in my environment and it looks fine:
```
$ helm3 lint smartcheck.tgz 
engine.go:136: [INFO] Missing required value: You must provide a value for auth.secretSeed. Use --set auth.secretSeed={password} or include a value in your overrides.yaml file.
...
```
The only difference I can see is my folder structure:
```
smartcheck-1.2.60/
smartcheck-1.2.60/Chart.yaml
smartcheck-1.2.60/templates/
smartcheck-1.2.60/templates/docs.yaml
...
```
My helm version is not new though.
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Let me know if this helps.

**Comment by rameshkjha** [comment]
It looks like an issue on Mac. I was able to package it on Linux machine and it went fine.

**Comment by warrenstephens** [comment]
Wow this is really inconvenient on the Mac!  I wasted a bunch of time before trying gtar.

**Comment by DarkStar1** [comment]
Gtar saved my arse too. Thanks

**Comment by markhv-code** [comment]
just want to thank gtar, worked flawlessly
