### ISSUE TITLE
Consider shortening helm setup guide

### ISSUE THREAD

**Issue by christopherhein** [deep-security/smartcheck-helm#5]
These 3 lines will shorten up the `helm` installation instructions and allow `helm` to be set up without an restarts from the pod not having proper access on an RBAC cluster.

```bash
$ kubectl -n kube-system create sa tiller
$ kubectl create clusterrolebinding tiller-cluster-rule \
    --clusterrole=cluster-admin \
    --serviceaccount=kube-system:tiller
$ helm init --service-account tiller
```

**Comment by glb** [comment]
Fixed in 68512903a921213fed953849d4139e3f119b75b4. Thanks again @christopherhein!
