### ISSUE TITLE
Error 405 when attempting to create session

### ISSUE THREAD

**Issue by kwkeefer** [deep-security/smartcheck-helm#6]
The GUI works fine as far as I can tell.  I'm trying to get started with using the API and am running into issues.  Not sure if it's because I'm still using the self-signed cert, but I didn't see anything in the documentation that said you needed to change the cert to use the APIs.   

```
curl  -k -d '{"user":{"userID":"api_user","password":"REDACTED"}}' \
-H "Content-Type: application/json" \
https://REDACTED.us-west-2.elb.amazonaws.com:443/sessions
```

Throws the following error:
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Also tried in Python using the Requests package and I'm getting the same thing:

```
import requests
import logging

logging.basicConfig(level=logging.DEBUG)

url = "https://REDACTED.us-west-2.elb.amazonaws.com:443/sessions"


api_pw = "REDACTED"

session = {
  "user": {
    "userID": "api_user",
    "password": api_pw
  }
}

r = requests.post(url, json=session, verify=False)
print(r.text)
```

Returns the following:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): REDACTED.us-west-2.elb.amazonaws.com
/Library/Python/2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://REDACTED.us-west-2.elb.amazonaws.com:443 "POST /sessions HTTP/1.1" 405 166
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by glb** [comment]
Hi @kwkeefer ! Sorry for the inconvenience. The base API endpoint is `/api`, so if you try your `POST` to `/api/sessions` things should work better.

The OpenAPI spec defines the `basePath` attribute, but this isn't being shown in the documentation. We've got a fix in progress but it won't be available until early January because of holiday schedules.

Please let us know if this helps!

**Comment by kwkeefer** [comment]
That worked, thanks!
