### ISSUE TITLE
Unable to install with helm v2.12.2

### ISSUE THREAD

**Issue by glb** [deep-security/smartcheck-helm#7]
Attempting to install this chart as a GitHub archive (`https://github.com/deep-security/smartcheck-helm/archive/master.tar.gz`) with helm v2.12.2 results in the following error:

```
Error: chart illegally contains empty path
```

**Comment by glb** [comment]
Investigation shows that helm v2.12.2 introduced some overly-aggressive checks on chart archive contents; when GitHub creates the archive there is an entry called `pax_global_header` that `helm` should ignore but treats as a security issue.

See helm/helm#5198, which has been merged and is tagged for inclusion in helm v2.12.3.

In the interim, use helm v2.12.1 to install Deep Security Smart Check.

**Comment by glb** [comment]
https://github.com/helm/helm/releases/tag/v2.12.3 has been released

**Comment by rameshkjha** [comment]
Here is my chart directory structure.
  helm
          /templates/
          Chart.yaml
          values.yaml
I am packaging helm directory, when I run helm lint on the generated package *.tgz file it is throwing this error.

==> Linting my_package_file.tgz
Error unable to extract tarball: chart illegally contains content outside the base directory: "._helm"

Error: 1 chart(s) linted, 1 chart(s) failed.

Helm version in use - Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
